module.exports = {
  FeatureName: 'DME Gnav',
  features: [
    {
      tcid: '1',
      name: '@desc-public-gnav',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na',
      tags: '@dme-gnav @anonymous',
    },
    {
      tcid: '2',
      name: '@desc-loggedin-gnav-loaded-for-member-user',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na',
      tags: '@dme-gnav @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Platinum',
          permissionRegion: 'Europe West',
        },
      },
    },
    {
      tcid: '3',
      name: '@desc-loggedin-gnav-not-loaded-for-non-member-user',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na',
      tags: '@dme-gnav @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'SPP',
          partnerLevel: 'Platinum',
          permissionRegion: 'Europe West',
        },
      },
    },
    {
      tcid: '4',
      name: '@desc-personalisation-non-logged-in-user',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        h3ElementId: 'partner-not-signed-in',
        h3ElementText: 'Partner NOT SIGNED IN',
      },
    },
    {
      tcid: '5',
      name: '@desc-personalisation-logged-in-non-member-user',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'SPP',
          partnerLevel: 'Platinum',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'partner-non-member',
        h3ElementText: 'Partner NON MEMBER',
      },
    },
    {
      tcid: '6',
      name: '@desc-personalisation-logged-in-member-registered-user',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Registered',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'member',
        h3ElementText: 'MEMBER',
        h3ElementRegisteredId: 'partner-registered',
        h3ElementRegisteredText: 'Partner REGISTERED',
        h3ElementResellerId: 'partner-reseller',
        h3ElementResellerText: 'Partner RESELLER',
      },
    },
    {
      tcid: '7',
      name: '@desc-personalisation-logged-in-member-certified-user',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Certified',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'member',
        h3ElementText: 'MEMBER',
        h3ElementCertifiedId: 'partner-certified',
        h3ElementCertifiedText: 'Partner CERTIFIED',
        h3ElementResellerId: 'partner-reseller',
        h3ElementResellerText: 'Partner RESELLER',
      },
    },
    {
      tcid: '8',
      name: '@desc-personalisation-logged-in-member-gold-user',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Gold',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'member',
        h3ElementText: 'MEMBER',
        h3ElementGoldId: 'partner-gold',
        h3ElementGoldText: 'Partner GOLD',
        h3ElementGoldDistributorId: 'partner-gold-distributor',
        h3ElementGoldDistributorText: 'Partner GOLD, DISTRIBUTOR',
        h3ElementResellerId: 'partner-reseller',
        h3ElementResellerText: 'Partner RESELLER',
      },
    },
    {
      tcid: '9',
      name: '@desc-personalisation-logged-in-member-platinum-user-with-first-name',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Platinum',
          firstName: 'Platinum Name',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'member',
        h3ElementText: 'MEMBER',
        h3ElementPlatinumFirstId: 'partner-platinum-first',
        h3ElementPlatinumFirstText: 'Partner PLATINUM First',
        h3ElementPlatinumSecondId: 'partner-platinum-second',
        h3ElementPlatinumSecondText: 'Partner PLATINUM Second',
        h3ElementResellerId: 'partner-reseller',
        h3ElementResellerText: 'Partner RESELLER',
      },
    },
    {
      tcid: '10',
      name: '@desc-personalisation-logged-in-member-platinum-user-without-first-name',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Platinum',
          firstName: '',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'member',
        h3ElementText: 'MEMBER',
        h3ElementPlatinumFirstId: 'partner-platinum-first',
        h3ElementPlatinumFirstText: 'Partner PLATINUM First',
        h3ElementPlatinumSecondId: 'partner-platinum-second',
        h3ElementPlatinumSecondText: 'Partner PLATINUM Second',
        platinumSecondDescriptionText: 'Featuring over 600,000 hand-picked stock photos and graphics',
        h3ElementResellerId: 'partner-reseller',
        h3ElementResellerText: 'Partner RESELLER',
      },
    },
    {
      tcid: '11',
      name: '@desc-personalisation-logged-in-member-distributor-user',
      path: '/channelpartners/drafts/automation/regression/personalized-page?akamaiLocale=na',
      tags: '@dme-gnav @personalisation @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Distributor',
          permissionRegion: 'Europe West',
        },
        h3ElementId: 'member',
        h3ElementText: 'MEMBER',
        h3ElementDistributorId: 'partner-distributor',
        h3ElementDistributorText: 'Partner DISTRIBUTOR',
        h3ElementGoldDistributorId: 'partner-gold-distributor',
        h3ElementGoldDistributorText: 'Partner GOLD, DISTRIBUTOR',
        h3ElementResellerId: 'partner-reseller',
      },
    },
  ],
};
