module.exports = {
  FeatureName: 'DX News page',
  features: [
    {
      tcid: '1',
      name: '@desc-regression-news-page-search',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      data: {
        publicCard1: 'Automation regression news card SPP Public no1',
        publicCard2: 'Automation regression news card SPP Public no2',
        cardDescription: 'This is automation',
        numberOfPublicCards: 9,
        numberOfMatchingDescCards: 7,
        numberOfMatchingTitleCards: 1,
      },
      tags: '@dx-news @regression @anonymous',
    },
    {
      tcid: '2',
      name: '@desc-regression-news-page-pagination-sort',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      data: {
        cardTitle: 'Automation regression news card SPP',
        firstLoadResult: '3 of 8 results',
        secondLoadResult: '6 of 8 results',
        thirdLoadResult: '8 of 8 results',
        numberOfCardsWithTitle: 8,
        numberOfPublicCards: 9,
      },
      tags: '@dx-news @regression @anonymous',
    },
    {
      tcid: '3',
      name: '@desc-regression-news-page-filters',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      data: {
        filterApplication: 'Applications',
        filterCampaign: 'Campaign',
        filterAnalytics: 'Analytics',
        filterAudience: 'Audience',
        filterTechnical: 'Technical',
        filterRegion: 'Region',
        filterAmericas: 'Americas',
        filterJapan: 'Japan',
        filterTopic: 'Topic',
        filterSolutions: 'Solutions',
        numberOfPublicCards: 9,
        cardsWithCampaign: 1,
        cardsWithCampaignAndAnalytics: 2,
        cardsWithTechnical: 1,
        cardsWithAmericasAndJapan: 3,
        cardsWithJapan: 1,
        cardsWithSolutions: 1,
      },
    },
    {
      tcid: '4',
      name: '@desc-regression-news-page-read-article',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      data: {
        cardTitle: 'Automation regression news card SPP Public no1',
        expectedToSeeInURL: '/solutionpartners/drafts/automation/regression/caas-cards/automation-regression-card-no1',
        cardsWithTitle: 1,
      },
      tags: '@dx-news @regression @anonymous',
    },
    {
      tcid: '5',
      name: '@desc-news-page-edge-cases',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      data: {
        dateInPast: 'Automation regression news card SPP with a date in the past',
        publicCard6: 'Automation regression news card SPP Public card no6',
        cardWithoutNewsCollection: 'Automation regression news card SPP Public without news collection tag',
        cardWithoutTitle: 'Without card title',
        cardWithSpecialChars: '? ! | <> * !@#$%^&*()_+~`<>?\\’|”{}][ уљађз',
        numberOfPublicCards: 9,
        noCards: 0,
        oneCard: 1,
      },
      tags: '@dx-news @regression @anonymous',
    },
    {
      tcid: '6',
      name: '@login-news-page-platinum-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      data: {
        platinumCard: 'Automation regression news card spp platinum no1',
        partnerLevel: 'Platinum',
        partnerPortal: 'SPP',
        expectedToSeeInURL: '/solutionpartners/drafts/'
          + 'automation/regression/caas-cards/automation-regression-platinum-card-no1',
        numberOfPublicCards: 9,
        noCards: 0,
        numberOfAllCards: 14,
        numberOfPlatinumCards: 1,
      },
    },
    {
      tcid: '7',
      name: '@login-news-page-gold-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      data: {
        partnerLevel: 'Gold',
        partnerPortal: 'SPP',
        resultTotal: 13,
        cardPartnerLevel: 'Automation regression news card SPP Gold no1',
        cardLevelAbove: 'Automation regression news card spp platinum no1',
        numberOfPublicCards: 9,
        partnerLevelCard: 1,
        noCards: 0,
      },
    },
    {
      tcid: '8',
      name: '@login-news-page-silver-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      data: {
        partnerLevel: 'Silver',
        partnerPortal: 'SPP',
        resultTotal: 12,
        cardPartnerLevel: 'Automation regression news card SPP Silver no1',
        cardLevelAbove: 'Automation regression news card spp gold no1',
        numberOfPublicCards: 9,
        partnerLevelCard: 1,
        noCards: 0,
      },
    },
    {
      tcid: '9',
      name: '@login-news-page-bronze-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      data: {
        partnerLevel: 'Bronze',
        partnerPortal: 'SPP',
        resultTotal: 11,
        cardPartnerLevel: 'Automation regression news card SPP Bronze no1',
        cardLevelAbove: 'Automation regression news card spp silver no1',
        numberOfPublicCards: 9,
        partnerLevelCard: 1,
        noCards: 0,
      },
    },
    {
      tcid: '10',
      name: '@login-news-page-community-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      data: {
        partnerLevel: 'Community',
        partnerPortal: 'SPP',
        resultTotal: 10,
        cardPartnerLevel: 'Automation regression news card SPP Community no1',
        cardLevelAbove: 'Automation regression news card spp bronze no1',
        numberOfPublicCards: 9,
        partnerLevelCard: 1,
        noCards: 0,
      },
    },
    {
      tcid: '11',
      name: '@login-news-page-non-member-of-spp-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @anonymous',
      baseURL: 'https://www.stage.adobe.com/partners.html',
      data: {
        partnerLevel: 'Platinum',
        partnerPortal: 'TPP',
        numberOfPublicCards: 9,
      },
    },
  ],
};
